import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "../components/AppWrapper"
import { ToastContainer } from "react-toastify";
import Provider from "../lib/session-provider/Provider";
import "react-toastify/dist/ReactToastify.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <AppWrapper>{children}</AppWrapper>
          <ToastContainer />
        </Provider>
      </body>
    </html>
  );
}
